export const CONTROLLER_METADATA_KEY = 'CONTROLLER_METADATA_KEY';
export const ACTION_METADATA_KEY = 'ACTION_METADATA_KEY';
export const PARAM_METADATA_KEY = 'PARAM_METADATA_KEY';
export const MIDDLEWARE_METADATA_KEY = 'MIDDLEWARE_METADATA_KEY';
export const INTERCEPTOR_METADATA_KEY = 'INTERCEPTOR_METADATA_KEY';